# Generated by Django 5.1.15 on 2026-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_by',
            field=models.CharField(default='SYSTEM', max_length=255),
        ),
    ]
