# Generated by Django 5.1.15 on 2026-07-23 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_domain_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('emails_per_month', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('next_billing_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='db.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='db.subscriptionplan')),
            ],
            options={
                'db_table': 'organization_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle_start', models.DateField()),
                ('billing_cycle_end', models.DateField()),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('recipients_sent', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_usage', to='db.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='db.organizationsubscription')),
            ],
            options={
                'db_table': 'email_usage',
                'indexes': [models.Index(fields=['subscription'], name='email_usage_subscri_66590d_idx'), models.Index(fields=['billing_cycle_end'], name='email_usage_billing_ca3326_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhonePeMandate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=150, unique=True)),
                ('merchant_subscription_id', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, max_length=20)),
                ('raw_response', models.JSONField(default=dict)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandate', to='db.organizationsubscription')),
            ],
            options={
                'db_table': 'phonepe_mandates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='phonepe_man_status_027ada_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=150, unique=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('response_code', models.CharField(blank=True, max_length=50)),
                ('response', models.JSONField(default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='db.organizationsubscription')),
            ],
            options={
                'db_table': 'subscription_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_e7dc37_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_c8a072_idx'), models.Index(fields=['payment_date'], name='subscriptio_payment_9349ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='db.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_plan_features',
                'indexes': [models.Index(fields=['plan', 'feature'], name='subscriptio_plan_id_8a23ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_1af930_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status'], name='organizatio_status_ed28b0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['expires_at'], name='organizatio_expires_22c005_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['next_billing_at'], name='organizatio_next_bi_86242f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['plan', 'status'], name='organizatio_plan_id_9e8616_idx'),
        ),
    ]
