# Generated by Django 5.1.15 on 2026-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_subscriptionplan_organizationsubscription_emailusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='next_billing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
