# Generated by Django 5.1.15 on 2026-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_organizationsubscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='merchant_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='merchant_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
