# Generated by Django 5.1.15 on 2026-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_organizationsubscription_merchant_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
