# Generated by Django 5.1.15 on 2026-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_supportticketmessages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='merchant_subscription_id',
            new_name='razorpay_invoice_id',
        ),
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='phonepe_transaction_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='razorpay_subscription_id',
            field=models.CharField(db_index=True, default='6ffbcb15-79c7-4ff2-b19f-474f6fac8938', max_length=150),
            preserve_default=False,
        ),
    ]
