# Generated by Django 5.1.15 on 2026-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_rename_merchant_subscription_id_subscriptionpayment_razorpay_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='razorpay_plan_id',
            field=models.CharField(db_index=True, default='375f2026-c49a-4c9d-bc20-41e167947c69', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
