# Generated by Django 5.1.15 on 2026-08-19 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_subscriptionplan_razorpay_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otp',
                'indexes': [models.Index(fields=['phone', 'expires_at', 'otp'], name='user_otp_phone_5ccca6_idx'), models.Index(fields=['email', 'expires_at', 'otp'], name='user_otp_email_ea5967_idx')],
            },
        ),
    ]
