# Generated by Django 5.1.15 on 2026-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_userotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['amount']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='analytics_level',
            field=models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('FULL', 'Full')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_api_keys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_verified_domains',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='emails_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
