# Generated by Django 5.1.15 on 2026-09-02 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_subscriptionpayment_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('updated_by', models.CharField(default='SYSTEM', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=20)),
                ('payment_gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('gateway_invoice_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='db.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='db.organizationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'transaction_type'], name='db_transact_organiz_e0453d_idx'), models.Index(fields=['organization', 'status'], name='db_transact_organiz_43a7f7_idx'), models.Index(fields=['status', 'created_at'], name='db_transact_status_2de7ad_idx')],
            },
        ),
    ]
