# Generated by Django 5.1.15 on 2026-09-02 13:23

import db.models.transaction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(db_index=True, default=db.models.transaction.generate_transaction_id, editable=False, max_length=30, unique=True),
        ),
    ]
