# Generated by Django 5.1.15 on 2026-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
