# Generated by Django 5.1.15 on 2026-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_organization_razorpay_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAUSED', 'Paused'), ('FAILED', 'Failed'), ('HALTED', 'Halted')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
